import numpy as np
dataset = np.array([23, 76, 34, 67, 89, 12, 90, 33, 22, 56, 78, 99, 45, 32])
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
min_val = np.min(dataset)
max_val = np.max(dataset)
print("Dataset:")
print(dataset)
print(f"Mean: {mean:.2f}")
print(f"Median: {median}")
print(f"Variance: {variance:.2f}")
print(f"Standard Deviation: {std_deviation:.2f}")
print(f"Minimum Value: {min_val}")
print(f"Maximum Value: {max_val}")